services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "3001:3001"
    env_file:
      - ./apps/http/.env
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
  validator:
    build:
      context: .
      dockerfile: docker/Dockerfile.validator
    ports:
      - "3003:3003"
    env_file:
      - ./apps/validator/.env
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        DB_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres
      - redis
  webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.webhook
    ports:
    - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
  redisdata:
