name: Docker Environment Validation

on:
  push:
    branches: [main]
    pull_request: 
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build all Docker Images
      run: docker compose -f docker-compose.dev.yaml build --pull

    - name: Start the Docker Images
      run: docker compose -f docker-compose.dev.yaml up -d
    
    - name: Sleep for 30 seconds
      run: sleep 30

    - name: Validate Prometheus readiness
      run: curl -f http://localhost:9090/-/ready

    - name: Validate Grafana health
      run: curl -f http://localhost:3005/api/health

    - name: Validate HTTP service
      run: curl -f http://localhost:3000/health

    - name: Validate Validator service
      run: curl -f http://localhost:3002/health

    - name: Validate Webhook service
      run: curl -f http://localhost:3003/health

    - name: Tear down Docker environment
      run: docker compose -f docker-compose.dev.yml down -v
