name: Docker Environment Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}  # ensures repo root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all Docker Images
        run: docker compose -f docker-compose.dev.yml build --pull

      - name: Start Docker environment
        run: docker compose -f docker-compose.dev.yml up -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Validate Prometheus readiness
        run: curl -f http://localhost:9090/-/ready

      - name: Validate Grafana health
        run: curl -f http://localhost:3001/api/health

      - name: Validate HTTP service
        run: curl -f http://localhost:3000/health

      - name: Validate Validator service
        run: curl -f http://localhost:3002/health

      - name: Validate Webhook service
        run: curl -f http://localhost:3003/health

      - name: Tear down Docker environment
        run: docker compose -f docker-compose.dev.yml down -v
